# https://jekyllrb.com/docs/configuration/

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
#collections:
#  posts:
#    output:   true

# Handling Reading
safe:                 false
include:              [".htaccess"]
exclude:              ["new-page.md"]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
verbose:  false
defaults: []

liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1


# --------------------------------------------

# Site Config
url: https://www.littlewhite.me
title: Little White
description:
feed_path: atom.xml
archive_path: archive.html
categories_path: categories.html
tags_path: tags.html
sitemap_path: sitemap.txt
tagline: Site Tagline

# Author Config
author :
  name : Skywalker
  email : xuotoa@gmail.com
  github : ericxiong

# Comment Config
comments:
  livere:
    enable: true
    id: MTAyMC8zMzMwNi85ODYz

## Analytics Config
analytics:
  google:
    enable: true
    id: UA-48846000-1
  baidu:
    enable: true
    id: 88bb8f0de1ddc1d016b5bf37e2aaf6c2

## Sharing Config
sharing:
